import type { Metadata } from "next";
import "./globals.css";
import { Yanone_Kaffeesatz } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const yanone = Yanone_Kaffeesatz({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans bg-background text-foreground ${yanone.className}`}
      >
        {children}
      </body>
    </html>
  );
}
